variable:
  profiles: local
spring:
  application:
    name: freecoin-notary-core
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/freecoin?characterEncoding=utf-8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters:
      # 初始化大小，最小，最大
      initial-size: 1
      max-active: 20
      min-idle: 1
      # 配置获取连接等待超时的时间
      max-wait: 5000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      # 配置监控页面密码登录
      stat-view-servlet:
        login-password: druid
        login-username: druid
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

eth:
  service: https://ropsten.infura.io/v3/072097a24b7c4994912ccd66991d5300
  contract:
    address: xxx
  wallet:
    path: /Users/pengyuxiang/freecoin/wallet1
  gaslimit: 21000

tron:
  fullnode:
    - 52.53.189.99:50051
    - 18.196.99.16:50051
    - 34.253.187.192:50051
    - 35.180.51.163:50051
    - 54.252.224.209:50051
    - 18.228.15.36:50051
    - 52.15.93.92:50051
    - 34.220.77.106:50051
    - 13.127.47.162:50051
    - 13.124.62.58:50051
  privateKeyHex:
  contractBase58Check: TFR879YysKW5XWUb2vK5W3oM1yz4VuLyWn
